### ISSUE TITLE
Fieldpaper with custom TMS results in empty (black pages) pdf

### ISSUE THREAD

**Issue by PaulUithol** [fieldpapers/fieldpapers#110]
See http://stamen-fieldpapers-dev.herokuapp.com/atlases/663sti68 or http://stamen-fieldpapers-dev.herokuapp.com/atlases/2ey1cmp9 for an example. This is using the Mapbox TMS on which we have our Drone aerial imagery for Dar es Salaam.

Steps to reproduce:

1. Start a new field paper around Dar es Salaam
2. Enter https://a.tiles.mapbox.com/v4/droneadv.l8kc6bho/{z}/{x}/{y}@2x.png?access_token=pk.eyJ1IjoiZHJvbmVhZHYiLCJhIjoiYmU0ZXQtcyJ9.8Fh95YZQ_WdYEDlgtmH95A as the TMS
3. (optional) Select a somewhat suitable area, instead of the whole city
4. Create the fieldpaper; I'm just using the defaults (map only, etc)
5. Download the pdf; it's just black.

**Comment by mojodna** [comment]
If you switch the TMS to use `http` instead of `https`, it should work.  The underlying problem is https://github.com/stamen/modestmaps-py/issues/10, which has been fixed but not released or incorporated into the renderer image.

**Comment by PaulUithol** [comment]
I'm still not able to produce a working fieldpaper with the above procedure, not when using `http://` either. Instead, an error is displayed; "Atlas creation failed". See http://stamen-fieldpapers-dev.herokuapp.com/atlases/6b5c2cou and http://stamen-fieldpapers-dev.herokuapp.com/atlases/1jt3did2.

With `https://`, the result is still the same; it works, but you get blackness (see http://stamen-fieldpapers-dev.herokuapp.com/atlases/2624v2of).

**Comment by mataharimhairi** [comment]
@mojodna Can this issue be re-opened? It appears to still be a problem.

**Comment by mojodna** [comment]
HTTPS works now, though this uncovered some weirdness when using custom TMSes...

This should work: `https://a.tiles.mapbox.com/v4/droneadv.l8kc6bho/{Z}/{X}/{Y}.png?access_token=pk.eyJ1IjoiZHJvbmVhZHYiLCJhIjoiYmU0ZXQtcyJ9.8Fh95YZQ_WdYEDlgtmH95A`

The differences are capital letters used in placeholders and not using retina (`@2x`) tiles.  I'm planning on fixing these through a combination of messaging and actual fixes.

**Comment by mojodna** [comment]
http://next.fieldpapers.org/atlases/3u4bd8en
