### ISSUE TITLE
Nonsquare page layout results in stretched and unreadable index page

### ISSUE THREAD

**Issue by liskin** [fieldpapers/fieldpapers#99]
See page 1 of https://s3.amazonaws.com/staging.files.fieldpapers.org/prints/17xj4d1o/atlas-17xj4d1o.pdf (http://next.fieldpapers.org/atlases/17xj4d1o).

**Comment by mojodna** [comment]
I have (and think I committed) a fix for this, although it could have been specific to non-index pages.

**Comment by mojodna** [comment]
(Thank you for reporting this!!)

**Comment by severinmenard** [comment]
Seems the issue still exists. I.e. see: 
http://fieldpapers.org/atlases/15hlma6i
http://fieldpapers.org/atlases/1bshaqvo
